name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Check Vercel Credentials & Deploy
        if: ${{ secrets.CUDAN != '' && secrets.ORG_ID != '' && secrets.PROJECT_ID != '' }}
        env:
          VERCEL_TOKEN: ${{ secrets.CUDAN }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: npx vercel --token=${{ secrets.CUDAN }} --prod --yes